/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facade.practice;

public class App {
    public static void main(String[] args) {
        TravelPackageFacade travelPackageFacade = new TravelPackageFacadeImpl();
        travelPackageFacade.book();
    }
}
